### PR TITLE
Write the service.

### PR DESCRIPTION
**Pull request by mithrandi**

### CODE REVIEW

**Comment by jonathanj** [comment]
Minor review points, otherwise this looks good. :+1:

<details><summary>

<i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary>



> #### Write the service.
> 
> </details>

---

Reviewed 13 of 21 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/Main.hs, line 27 [r1]](https://reviewable.io:443/reviews/fusionapp/catcher-in-the-rye/1#-KI79ukiXa0O4cHSKilx:-KI79ukiXa0O4cHSKily:-484069531) ([raw file](https://github.com/fusionapp/catcher-in-the-rye/blob/f9f9b9c00dad7cb6eaca99b5c21ced16ef68a4f5/app/Main.hs#L27)):_

> ``` Haskell
> -- | Schedule uploads to a particular destination.
> scheduleUpload :: ConnectionPool
>                -- ^ Aapplication DB connection pool.
> ```

Typo.

---

_[app/Main.hs, line 57 [r1]](https://reviewable.io:443/reviews/fusionapp/catcher-in-the-rye/1#-KI7FusipM8LzDspXtbN:-KI7FusipM8LzDspXtbO:-1484241988) ([raw file](https://github.com/fusionapp/catcher-in-the-rye/blob/f9f9b9c00dad7cb6eaca99b5c21ced16ef68a4f5/app/Main.hs#L57)):_

> ``` Haskell
>     Nothing -> run port wapp
>       where port = fromMaybe 8080 . view configHttpPort $ config
> 
> ```

Extraneous whitespace.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/catcher-in-the-rye/1#-:-KIC9LVRcMfb6OcAz9xL:-1471662148)_

**Comment by mithrandi** [comment]
Review status: 21 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/Main.hs, line 27 [r1]](https://reviewable.io:443/reviews/fusionapp/catcher-in-the-rye/1#-KI79ukiXa0O4cHSKilx:-KICAtRpsl4kBQfQeogt:1758359711) ([raw file](https://github.com/fusionapp/catcher-in-the-rye/blob/f9f9b9c00dad7cb6eaca99b5c21ced16ef68a4f5/app/Main.hs#L27)):_
<details><summary>

<i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary>



> Typo.
> </details>
> Fixed.

---

_[app/Main.hs, line 57 [r1]](https://reviewable.io:443/reviews/fusionapp/catcher-in-the-rye/1#-KI7FusipM8LzDspXtbN:-KICB-6I5vROdG_b5tPC:1758359711) ([raw file](https://github.com/fusionapp/catcher-in-the-rye/blob/f9f9b9c00dad7cb6eaca99b5c21ced16ef68a4f5/app/Main.hs#L57)):_
<details><summary>

<i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary>



> Extraneous whitespace.
> </details>
> Fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/catcher-in-the-rye/1)_

**Comment by jonathanj** [comment]
Reviewed 1 of 1 files at r3.
Review status: 21 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/catcher-in-the-rye/1)_

**Comment by jonathanj** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/catcher-in-the-rye/1)_

**Pull request merged**
